// Mapping of Figi exchange code to currency
// based on heuristic of using the country code and mapping
// the country to its currency
// The exchange code mapping is from this document:
// https://www.inforeachinc.com/bloomberg-exchange-code-mapping
export const EXCHANGE_CODE_TO_CURRENCY: Record<string, string> = {
	CK: 'CZK',
	CD: 'CZK',
	CP: 'CZK',
	KL: 'CZK',
	RC: 'CZK',
	UP: 'USD',
	UF: 'USD',
	VY: 'USD',
	UO: 'USD',
	VJ: 'USD',
	VK: 'USD',
	'ISLAND ECN LTD': 'USD',
	VF: 'USD',
	UV: 'USD',
	PQ: 'USD',
	UT: 'USD',
	UD: 'USD',
	UA: 'USD',
	UM: 'USD',
	UC: 'USD',
	UL: 'USD',
	UR: 'USD',
	UW: 'USD',
	UQ: 'USD',
	UN: 'USD',
	UU: 'USD',
	UX: 'USD',
	AV: 'EUR',
	XA: 'EUR',
	CY: 'EUR',
	YC: 'EUR',
	ET: 'EUR',
	FF: 'EUR',
	FH: 'EUR',
	QE: 'EUR',
	M0: 'EUR',
	FP: 'EUR',
	GW: 'EUR',
	PG: 'EUR',
	GZ: 'EUR',
	BQ: 'EUR',
	GQ: 'EUR',
	GE: 'EUR',
	GT: 'EUR',
	GF: 'EUR',
	XD: 'EUR',
	TH: 'EUR',
	GH: 'EUR',
	GI: 'EUR',
	GM: 'EUR',
	QT: 'EUR',
	GS: 'EUR',
	XS: 'EUR',
	AA: 'EUR',
	XT: 'EUR',
	AP: 'EUR',
	GA: 'EUR',
	L1: 'EUR',
	XF: 'EUR',
	PO: 'EUR',
	TE: 'EUR',
	HM: 'EUR',
	IM: 'EUR',
	IC: 'EUR',
	XI: 'EUR',
	IF: 'EUR',
	LG: 'EUR',
	LH: 'EUR',
	LX: 'EUR',
	MV: 'EUR',
	E2: 'EUR',
	B4: 'EUR',
	X2: 'EUR',
	I2: 'EUR',
	X1: 'EUR',
	T1: 'EUR',
	X9: 'EUR',
	WT: 'EUR',
	NA: 'EUR',
	PL: 'EUR',
	SV: 'EUR',
	XJ: 'EUR',
	SN: 'EUR',
	SQ: 'EUR',
	SA: 'EUR',
	ID: 'EUR',
}

export type Exchange = {
	currency: string
	exchange: string
	mic: string
	operatingMic: string
	micExchangeName: string
	country: string
}

export const EXCHANGES: Record<string, Exchange> = {
	CK: {
		currency: 'CZK',
		exchange: 'PRAGUE SE',
		mic: 'XPRA',
		operatingMic: 'XPRA',
		micExchangeName: 'PRAGUE STOCK EXCHANGE',
		country: 'CZ',
	},
	CD: {
		currency: 'CZK',
		exchange: 'PRAGUE-SPAD',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'CZ',
	},
	KL: {
		currency: 'CZK',
		exchange: 'PRAGUE-BLOCK',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'CZ',
	},
	RC: {
		currency: 'CZK',
		exchange: 'CZECH OTC',
		mic: 'XRMZ',
		operatingMic: 'XRMZ',
		micExchangeName: 'RM-SYSTEM CZECH STOCK EXCHANGE',
		country: 'CZ',
	},
	UP: {
		currency: 'USD',
		exchange: 'NYSE ARCA',
		mic: 'ARCX',
		operatingMic: 'XNYS',
		micExchangeName: 'NYSE ARCA',
		country: 'US',
	},
	UF: {
		currency: 'USD',
		exchange: 'CBOE BZX',
		mic: 'BATS',
		operatingMic: 'XCBO',
		micExchangeName: 'CBOE BZX U.S. EQUITIES EXCHANGE',
		country: 'US',
	},
	VY: {
		currency: 'USD',
		exchange: 'CBOE BYX',
		mic: 'BATY',
		operatingMic: 'XCBO',
		micExchangeName: 'CBOE BYX U.S. EQUITIES EXCHANGE',
		country: 'US',
	},
	UO: {
		currency: 'USD',
		exchange: 'CBSX',
		mic: 'CBSX',
		operatingMic: 'XCBO',
		micExchangeName: 'CBOE STOCK EXCHANGE',
		country: 'US',
	},
	VJ: {
		currency: 'USD',
		exchange: 'EDGA',
		mic: 'EDGA',
		operatingMic: 'XCBO',
		micExchangeName: 'CBOE EDGA U.S. EQUITIES EXCHANGE',
		country: 'US',
	},
	VK: {
		currency: 'USD',
		exchange: 'EDGX',
		mic: 'EDGX',
		operatingMic: 'XCBO',
		micExchangeName: 'CBOE EDGX U.S. EQUITIES EXCHANGE',
		country: 'US',
	},
	'ISLAND ECN LTD': {
		currency: 'USD',
		exchange: 'UI',
		mic: 'ICEL',
		operatingMic: 'ICEL',
		micExchangeName: '"ISLAND ECN LTD',
		country: 'US',
	},
	VF: {
		currency: 'USD',
		exchange: 'INVESTOR  EX',
		mic: 'IEXG',
		operatingMic: 'IEXG',
		micExchangeName: 'INVESTORS EXCHANGE',
		country: 'US',
	},
	UV: {
		currency: 'USD',
		exchange: 'OTC US',
		mic: 'OOTC',
		operatingMic: 'FINR',
		micExchangeName: 'OTC BULLETIN BOARD - OTHER OTC',
		country: 'US',
	},
	PQ: {
		currency: 'USD',
		exchange: 'OTC MARKETS',
		mic: 'OTCM',
		operatingMic: 'OTCM',
		micExchangeName: 'OTC PINK MARKETPLACE',
		country: 'US',
	},
	UT: {
		currency: 'USD',
		exchange: 'NASDAQ IM',
		mic: 'XNIM',
		operatingMic: 'XNAS',
		micExchangeName: 'NASDAQ INTERMARKET',
		country: 'US',
	},
	UD: {
		currency: 'USD',
		exchange: 'FINRA ADF',
		mic: 'XADF',
		operatingMic: 'FINR',
		micExchangeName: 'FINRA ALTERNATIVE DISPLAY FACILITY',
		country: 'US',
	},
	UA: {
		currency: 'USD',
		exchange: 'NYSEAMERICAN',
		mic: 'XASE',
		operatingMic: 'XNYS',
		micExchangeName: 'NYSE MKT LLC',
		country: 'US',
	},
	UM: {
		currency: 'USD',
		exchange: 'NYSE CHICAGO',
		mic: 'XCHI',
		operatingMic: 'XCHI',
		micExchangeName: 'NYSE CHICAGO INC',
		country: 'US',
	},
	UC: {
		currency: 'USD',
		exchange: 'NYSE NATIONAL',
		mic: 'XCIS',
		operatingMic: 'XCIS',
		micExchangeName: 'NYSE NATIONAL INC',
		country: 'US',
	},
	UL: {
		currency: 'USD',
		exchange: 'ISE',
		mic: 'XISE',
		operatingMic: 'XISX',
		micExchangeName: 'INTERNATIONAL SECURITIES EXCHANGE LLC - EQUITIES',
		country: 'US',
	},
	UR: {
		currency: 'USD',
		exchange: 'NASDAQ CM',
		mic: 'XNCM',
		operatingMic: 'XNAS',
		micExchangeName: 'NASDAQ CAPITAL MARKET',
		country: 'US',
	},
	UW: {
		currency: 'USD',
		exchange: 'NASDAQ GS',
		mic: 'XNGS',
		operatingMic: 'XNAS',
		micExchangeName: 'NASDAQ/NGS (GLOBAL SELECT MARKET)',
		country: 'US',
	},
	UQ: {
		currency: 'USD',
		exchange: 'NASDAQ GM',
		mic: 'XNMS',
		operatingMic: 'XNAS',
		micExchangeName: 'NASDAQ/NMS (GLOBAL MARKET)',
		country: 'US',
	},
	UN: {
		currency: 'USD',
		exchange: 'NEW YORK',
		mic: 'XNYS',
		operatingMic: 'XNYS',
		micExchangeName: 'NEW YORK STOCK EXCHANGE INC',
		country: 'US',
	},
	UU: {
		currency: 'USD',
		exchange: 'OTC BB',
		mic: 'XOTC',
		operatingMic: 'XOTC',
		micExchangeName: 'OTC BULLETIN BOARD',
		country: 'US',
	},
	UX: {
		currency: 'USD',
		exchange: 'NSDQ OMX PSX',
		mic: 'XPSX',
		operatingMic: 'XNAS',
		micExchangeName: 'NASDAQ OMX PSX',
		country: 'US',
	},
	AV: {
		currency: 'EUR',
		exchange: 'VIENNA',
		mic: 'XWBO',
		operatingMic: 'XWBO',
		micExchangeName: 'WIENER BOERSE AG',
		country: 'AT',
	},
	XA: {
		currency: 'EUR',
		exchange: 'CEESEG OTC',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'AT',
	},
	CY: {
		currency: 'EUR',
		exchange: 'NICOSIA',
		mic: 'XCYS',
		operatingMic: 'XCYS',
		micExchangeName: 'CYPRUS STOCK EXCHANGE',
		country: 'CY',
	},
	YC: {
		currency: 'EUR',
		exchange: 'CYPRUS ECM',
		mic: 'XECM',
		operatingMic: 'XCYS',
		micExchangeName: 'CYPRUS ECM',
		country: 'CY',
	},
	ET: {
		currency: 'EUR',
		exchange: 'TALLINN',
		mic: 'XTAL',
		operatingMic: 'XTAL',
		micExchangeName: 'NASDAQ TALLINN AS',
		country: 'EE',
	},
	FF: {
		currency: 'EUR',
		exchange: 'FN FINLAND',
		mic: 'FNFI',
		operatingMic: 'XHEL',
		micExchangeName: 'FIRST NORTH FINLAND',
		country: 'FI',
	},
	FH: {
		currency: 'EUR',
		exchange: 'HELSINKI',
		mic: 'XHEL',
		operatingMic: 'XHEL',
		micExchangeName: 'NASDAQ HELSINKI LTD',
		country: 'FI',
	},
	QE: {
		currency: 'EUR',
		exchange: 'AQUIS - EU',
		mic: 'AQEU',
		operatingMic: 'AQEU',
		micExchangeName: 'AQUIS EXCHANGE EUROPE',
		country: 'FR',
	},
	M0: {
		currency: 'EUR',
		exchange: 'MS MTF',
		mic: 'MSAX',
		operatingMic: 'MSAX',
		micExchangeName: 'MORGAN STANLEY MTF - PERIODIC AUCTION',
		country: 'FR',
	},
	FP: {
		currency: 'EUR',
		exchange: 'PARIS',
		mic: 'XPAR',
		operatingMic: 'XPAR',
		micExchangeName: 'NYSE EURONEXT - EURONEXT PARIS',
		country: 'FR',
	},
	GW: {
		currency: 'EUR',
		exchange: 'STUTGT WRNTS',
		mic: 'EUWX',
		operatingMic: 'XSTU',
		micExchangeName: 'EUWAX',
		country: 'DE',
	},
	PG: {
		currency: 'EUR',
		exchange: 'PLUS EUROPE',
		mic: 'PLUS',
		operatingMic: 'PLUS',
		micExchangeName: 'BOERSE MUENCHEN - FREIVERKEHR',
		country: 'DE',
	},
	GZ: {
		currency: 'EUR',
		exchange: 'GETTEX',
		mic: 'MUND',
		operatingMic: 'XMUN',
		micExchangeName: 'BOERSE MUENCHEN – GETTEX – FREIVERKEHR',
		country: 'DE',
	},
	BQ: {
		currency: 'EUR',
		exchange: 'EQUIDUCT',
		mic: 'XEQT',
		operatingMic: 'XBER',
		micExchangeName: 'BOERSE BERLIN EQUIDUCT TRADING',
		country: 'DE',
	},
	GQ: {
		currency: 'EUR',
		exchange: 'XETRA STARS',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'DE',
	},
	GE: {
		currency: 'EUR',
		exchange: 'XTRA EU STARS',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'DE',
	},
	GT: {
		currency: 'EUR',
		exchange: 'XETRA ETF',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'DE',
	},
	GF: {
		currency: 'EUR',
		exchange: 'FRANKFURT',
		mic: 'XFRA',
		operatingMic: 'XFRA',
		micExchangeName: 'DEUTSCHE BOERSE AG',
		country: 'DE',
	},
	XD: {
		currency: 'EUR',
		exchange: 'DEUTSCHE OTC',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'DE',
	},
	TH: {
		currency: 'EUR',
		exchange: 'TRADEGATE',
		mic: 'XGAT',
		operatingMic: 'TGAT',
		micExchangeName: 'TRADEGATE',
		country: 'DE',
	},
	GH: {
		currency: 'EUR',
		exchange: 'HAMBURG',
		mic: 'XHAM',
		operatingMic: 'XHAM',
		micExchangeName: 'HANSEATISCHE WERTPAPIERBOERSE HAMBURG',
		country: 'DE',
	},
	GI: {
		currency: 'EUR',
		exchange: 'HANNOVER',
		mic: 'XHAN',
		operatingMic: 'XHAN',
		micExchangeName: 'NIEDERSAECHSISCHE BOERSE ZU HANNOVER',
		country: 'DE',
	},
	GM: {
		currency: 'EUR',
		exchange: 'MUNICH',
		mic: 'XMUN',
		operatingMic: 'XMUN',
		micExchangeName: 'BOERSE MUENCHEN',
		country: 'DE',
	},
	QT: {
		currency: 'EUR',
		exchange: 'Quotrix Exch',
		mic: 'XQTX',
		operatingMic: 'XDUS',
		micExchangeName: 'BOERSE DUESSELDORF - QUOTRIX',
		country: 'DE',
	},
	GS: {
		currency: 'EUR',
		exchange: 'STUTTGART',
		mic: 'XSTU',
		operatingMic: 'XSTU',
		micExchangeName: 'BOERSE STUTTGART',
		country: 'DE',
	},
	XS: {
		currency: 'EUR',
		exchange: 'STUTTGRT OTC',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'DE',
	},
	AA: {
		currency: 'EUR',
		exchange: 'ATHENS ALT',
		mic: 'ENAX',
		operatingMic: 'ASEX',
		micExchangeName: 'ATHENS EXCHANGE ALTERNATIVE MARKET',
		country: 'GR',
	},
	XT: {
		currency: 'EUR',
		exchange: 'ATHENS OTC',
		mic: 'HOTC',
		operatingMic: 'ASEX',
		micExchangeName: 'HELLENIC EXCHANGE OTC MARKET',
		country: 'GR',
	},
	AP: {
		currency: 'EUR',
		exchange: 'ATHENS REPO',
		mic: 'XADE',
		operatingMic: 'ASEX',
		micExchangeName: 'ATHENS EXCHANGE S.A. DERIVATIVES MARKET',
		country: 'GR',
	},
	GA: {
		currency: 'EUR',
		exchange: 'ATHENS',
		mic: 'XATH',
		operatingMic: 'ASEX',
		micExchangeName: 'ATHENS EXCHANGE S.A. CASH MARKET',
		country: 'GR',
	},
	L1: {
		currency: 'EUR',
		exchange: 'LIQUIDNET IR',
		mic: 'LEUE',
		operatingMic: 'LEUE',
		micExchangeName: 'LIQUIDNET EU LIMITED EQUITY MTF',
		country: 'IE',
	},
	XF: {
		currency: 'EUR',
		exchange: 'DUBLIN SE OTC',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'IE',
	},
	PO: {
		currency: 'EUR',
		exchange: 'ITG POSIT',
		mic: 'XPOS',
		operatingMic: 'ITGL',
		micExchangeName: 'POSIT DARK',
		country: 'IE',
	},
	TE: {
		currency: 'EUR',
		exchange: 'EUROTLX',
		mic: 'ETLX',
		operatingMic: 'ETLX',
		micExchangeName: 'EUROTLX',
		country: 'IT',
	},
	HM: {
		currency: 'EUR',
		exchange: 'HI-MTF',
		mic: 'HMTF',
		operatingMic: 'HMTF',
		micExchangeName: 'HI-MTF',
		country: 'IT',
	},
	IM: {
		currency: 'EUR',
		exchange: 'BRSAITALIANA',
		mic: 'MTAA',
		operatingMic: 'XMIL',
		micExchangeName: 'ELECTRONIC SHARE MARKET',
		country: 'IT',
	},
	IC: {
		currency: 'EUR',
		exchange: 'MIL COMP DAY',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'IT',
	},
	XI: {
		currency: 'EUR',
		exchange: 'BORSAITALOTC',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'IT',
	},
	IF: {
		currency: 'EUR',
		exchange: 'MIL AFTR HRS',
		mic: 'MTAH',
		operatingMic: 'XMIL',
		micExchangeName: 'BORSA ITALIANA EQUITY MTF',
		country: 'IT',
	},
	LG: {
		currency: 'EUR',
		exchange: 'RIGA',
		mic: 'XRIS',
		operatingMic: 'XRIS',
		micExchangeName: 'NASDAQ RIGA AS',
		country: 'LV',
	},
	LH: {
		currency: 'EUR',
		exchange: 'VILNIUS SE',
		mic: 'XLIT',
		operatingMic: 'XLIT',
		micExchangeName: 'AB NASDAQ VILNIUS',
		country: 'LT',
	},
	LX: {
		currency: 'EUR',
		exchange: 'LUXEMBOURG',
		mic: 'XLUX',
		operatingMic: 'XLUX',
		micExchangeName: 'LUXEMBOURG STOCK EXCHANGE',
		country: 'LU',
	},
	MV: {
		currency: 'EUR',
		exchange: 'VALETTA',
		mic: 'XMAL',
		operatingMic: 'XMAL',
		micExchangeName: 'MALTA STOCK EXCHANGE',
		country: 'MT',
	},
	E2: {
		currency: 'EUR',
		exchange: 'CBOE BXE EU',
		mic: 'BEUE',
		operatingMic: 'CCXE',
		micExchangeName: 'CBOE EUROPE - BXE ORDER BOOKS (NL)',
		country: 'NL',
	},
	B4: {
		currency: 'EUR',
		exchange: 'BMTF EU',
		mic: 'BTFE',
		operatingMic: 'BTFE',
		micExchangeName: 'BLOOMBERG TRADING FACILITY B.V.',
		country: 'NL',
	},
	X2: {
		currency: 'EUR',
		exchange: 'CBOE APA EU',
		mic: 'CAPA',
		operatingMic: 'CCXE',
		micExchangeName: 'CBOE EUROPE - APA (NL)',
		country: 'NL',
	},
	I2: {
		currency: 'EUR',
		exchange: 'CBOE DXE',
		mic: 'CEUX',
		operatingMic: 'CCXE',
		micExchangeName: 'CBOE EUROPE - DXE ORDER BOOKS (NL)',
		country: 'NL',
	},
	X1: {
		currency: 'EUR',
		exchange: 'TRADEECHO APA',
		mic: 'ECEU',
		operatingMic: 'ECEU',
		micExchangeName: 'TRADECHO EU APA',
		country: 'NL',
	},
	T1: {
		currency: 'EUR',
		exchange: 'Turquoise Eu',
		mic: 'TQEX',
		operatingMic: 'TQEX',
		micExchangeName: 'TURQUOISE EUROPE',
		country: 'NL',
	},
	X9: {
		currency: 'EUR',
		exchange: 'TW APA EU',
		mic: 'TWEA',
		operatingMic: 'TWEU',
		micExchangeName: 'TRADEWEB EU BV - APA',
		country: 'NL',
	},
	WT: {
		currency: 'EUR',
		exchange: 'TW MTF EU',
		mic: 'TWEM',
		operatingMic: 'TWEU',
		micExchangeName: 'TRADEWEB EU BV - MTF',
		country: 'NL',
	},
	NA: {
		currency: 'EUR',
		exchange: 'EN AMSTERDAM',
		mic: 'XAMS',
		operatingMic: 'XAMS',
		micExchangeName: 'NYSE EURONEXT - EURONEXT AMSTERDAM',
		country: 'NL',
	},
	PL: {
		currency: 'EUR',
		exchange: 'EN LISBON',
		mic: 'XLIS',
		operatingMic: 'XLIS',
		micExchangeName: 'OPERADOR DE MERCADO IBERICO DE ENERGIA - PORTUGAL',
		country: 'PT',
	},
	SV: {
		currency: 'EUR',
		exchange: 'LJUBLJANA',
		mic: 'XLJU',
		operatingMic: 'XLJU',
		micExchangeName: 'LJUBLJANA STOCK EXCHANGE (OFFICIAL MARKET)',
		country: 'SI',
	},
	XJ: {
		currency: 'EUR',
		exchange: 'LJUB SE OTC',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'SI',
	},
	SN: {
		currency: 'EUR',
		exchange: 'BME OUTCRY',
		mic: 'XMAD',
		operatingMic: 'BMEX',
		micExchangeName: 'BOLSA DE MADRID',
		country: 'ES',
	},
	SQ: {
		currency: 'EUR',
		exchange: 'SOC.BOL SIBE',
		mic: '',
		operatingMic: '',
		micExchangeName: '',
		country: 'ES',
	},
	SA: {
		currency: 'EUR',
		exchange: 'VALENCIA',
		mic: 'XVAL',
		operatingMic: 'BMEX',
		micExchangeName: 'BOLSA DE VALENCIA',
		country: 'ES',
	},
	ID: {
		currency: 'EUR',
		exchange: 'DUBLIN',
		mic: 'XDUB',
		operatingMic: 'XDUB',
		micExchangeName: 'IRISH STOCK EXCHANGE - MAIN MARKET',
		country: 'IE',
	},
}
