alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: kalkul.app
    type: PRIMARY
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: kalkul-app
      match:
        path:
          prefix: /
name: kalkul
region: fra
services:
  - build_command: pnpm build
    environment_slug: node-js
    envs:
      - key: PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${PUBLIC_SUPABASE_ANON_KEY}
      - key: PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${PUBLIC_SUPABASE_URL}
      - key: PUBLIC_ORIGIN
        scope: RUN_AND_BUILD_TIME
        value: ${PUBLIC_ORIGIN}
      - key: SUPABASE_JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${SUPABASE_JWT_SECRET}
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${SUPABASE_SERVICE_ROLE_KEY}
      - key: STRIPE_API_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${STRIPE_API_KEY}
      - key: PUBLIC_DISABLE_PAYWALL
        scope: RUN_AND_BUILD_TIME
        value: ${PUBLIC_DISABLE_PAYWALL}
      - key: PORT
        scope: RUN_TIME
        value: 8080
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: HOST
        scope: RUN_TIME
        value: 0.0.0.0
      - key: COREPACK_INTEGRITY_KEYS
        scope: RUN_AND_BUILD_TIME
        value: 0
    github:
      branch: main
      deploy_on_push: true
      repo: snaha/kalkul
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: kalkul-app
    run_command: node build/index.js
    source_dir: /
