create table "public"."transaction" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "amount" numeric not null,
    "date" timestamp with time zone not null,
    "end_date" timestamp with time zone,
    "investment_id" bigint not null,
    "label" text,
    "repeat" bigint,
    "repeat_unit" text,
    "type" text not null,
    "last_edited_at" timestamp with time zone default now()
);


alter table "public"."transaction" enable row level security;

CREATE UNIQUE INDEX transaction_pkey ON public.transaction USING btree (id);

alter table "public"."transaction" add constraint "transaction_pkey" PRIMARY KEY using index "transaction_pkey";

alter table "public"."transaction" add constraint "transaction_investment_id_fkey" FOREIGN KEY (investment_id) REFERENCES investment(id) not valid;

alter table "public"."transaction" validate constraint "transaction_investment_id_fkey";

alter table "public"."transaction" add constraint "transaction_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."transaction" validate constraint "transaction_user_id_fkey";

grant delete on table "public"."transaction" to "anon";

grant insert on table "public"."transaction" to "anon";

grant references on table "public"."transaction" to "anon";

grant select on table "public"."transaction" to "anon";

grant trigger on table "public"."transaction" to "anon";

grant truncate on table "public"."transaction" to "anon";

grant update on table "public"."transaction" to "anon";

grant delete on table "public"."transaction" to "authenticated";

grant insert on table "public"."transaction" to "authenticated";

grant references on table "public"."transaction" to "authenticated";

grant select on table "public"."transaction" to "authenticated";

grant trigger on table "public"."transaction" to "authenticated";

grant truncate on table "public"."transaction" to "authenticated";

grant update on table "public"."transaction" to "authenticated";

grant delete on table "public"."transaction" to "service_role";

grant insert on table "public"."transaction" to "service_role";

grant references on table "public"."transaction" to "service_role";

grant select on table "public"."transaction" to "service_role";

grant trigger on table "public"."transaction" to "service_role";

grant truncate on table "public"."transaction" to "service_role";

grant update on table "public"."transaction" to "service_role";

create policy "Enable all for users based on user_id"
on "public"."transaction"
as permissive
for all
to public
using ((( SELECT auth.uid() AS uid) = user_id));

alter publication supabase_realtime add table public.transaction;
