create table "public"."portfolio" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "last_edited_at" timestamp with time zone not null default now(),
    "start_date" date not null,
    "end_date" date not null,
    "inflation_rate" numeric not null,
    "client" bigint not null,
    "currency" text not null
);


CREATE UNIQUE INDEX portfolio_pkey ON public.portfolio USING btree (id);

alter table "public"."portfolio" add constraint "portfolio_pkey" PRIMARY KEY using index "portfolio_pkey";

alter table "public"."portfolio" add constraint "portfolio_client_fkey" FOREIGN KEY (client) REFERENCES client(id) not valid;

alter table "public"."portfolio" validate constraint "portfolio_client_fkey";

grant delete on table "public"."portfolio" to "anon";

grant insert on table "public"."portfolio" to "anon";

grant references on table "public"."portfolio" to "anon";

grant select on table "public"."portfolio" to "anon";

grant trigger on table "public"."portfolio" to "anon";

grant truncate on table "public"."portfolio" to "anon";

grant update on table "public"."portfolio" to "anon";

grant delete on table "public"."portfolio" to "authenticated";

grant insert on table "public"."portfolio" to "authenticated";

grant references on table "public"."portfolio" to "authenticated";

grant select on table "public"."portfolio" to "authenticated";

grant trigger on table "public"."portfolio" to "authenticated";

grant truncate on table "public"."portfolio" to "authenticated";

grant update on table "public"."portfolio" to "authenticated";

grant delete on table "public"."portfolio" to "service_role";

grant insert on table "public"."portfolio" to "service_role";

grant references on table "public"."portfolio" to "service_role";

grant select on table "public"."portfolio" to "service_role";

grant trigger on table "public"."portfolio" to "service_role";

grant truncate on table "public"."portfolio" to "service_role";

grant update on table "public"."portfolio" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."portfolio"
as permissive
for insert
to authenticated
with check (true);

alter publication supabase_realtime add table public.portfolio;