create table "public"."market_data_cache" (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    identifier text not null,
    id_type text not null,
    response_data json not null,
    constraint market_data_cache_pkey primary key (id),
    constraint market_data_cache_identifier_id_type_unique unique (identifier, id_type)
);

create index "market_data_cache_identifier_idx" on "public"."market_data_cache" using btree (identifier);
create index "market_data_cache_updated_at_idx" on "public"."market_data_cache" using btree (updated_at);

alter table "public"."market_data_cache" enable row level security;

-- Add trigger to automatically update updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger update_market_data_cache_updated_at
    before update on market_data_cache
    for each row
    execute function update_updated_at_column();
