create table
  public.isin_errors (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    identifier text null,
    error json null,
    constraint isin_errors_pkey primary key (id)
  ) tablespace pg_default;

alter policy "Enable insert for authenticated users only"
on "public"."isin_errors"
to authenticated
with check (
    true
);
