-- Create stripe_subscription table (singular naming convention)
CREATE TABLE stripe_subscription (
  id bigint generated by default as identity not null primary key,
  stripe_customer_id text NOT NULL UNIQUE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  stripe_subscription_id text NOT NULL UNIQUE,
  status text NOT NULL,
  current_period_end timestamptz NOT NULL,
  trial_end timestamptz,
  items jsonb,
  created_at timestamptz DEFAULT NOW() NOT NULL,
  last_edited_at timestamptz DEFAULT NOW() NOT NULL
);

-- Create index for faster lookups by user_id
CREATE INDEX idx_stripe_subscription_user_id ON stripe_subscription(user_id);

-- Create index for faster lookups by stripe_subscription_id
CREATE INDEX idx_stripe_subscription_subscription_id ON stripe_subscription(stripe_subscription_id);

-- Create index for faster lookups by stripe_customer_id
CREATE INDEX idx_stripe_subscription_customer_id ON stripe_subscription(stripe_customer_id);

-- Create last_edited_at trigger
CREATE OR REPLACE FUNCTION update_last_edited_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.last_edited_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_stripe_subscription_last_edited_at
  BEFORE UPDATE ON stripe_subscription
  FOR EACH ROW
  EXECUTE FUNCTION update_last_edited_at_column();