-- Add goal_data column to investment table
-- goal_data contains type field which identifies the goal type
ALTER TABLE "public"."investment"
ADD COLUMN "goal_data" JSONB;

-- Add check constraint: if goal_data exists, it must have type
ALTER TABLE "public"."investment"
ADD CONSTRAINT "investment_goal_data_check"
CHECK (
  goal_data IS NULL OR
  (goal_data IS NOT NULL AND goal_data->>'type' IS NOT NULL)
);

-- Create goal_investment_link table
CREATE TABLE "public"."goal_investment_link" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "goal_id" BIGINT NOT NULL REFERENCES "public"."investment"("id") ON DELETE CASCADE,
  "investment_id" BIGINT NOT NULL REFERENCES "public"."investment"("id") ON DELETE CASCADE,
  "percentage" NUMERIC NULL CHECK (percentage IS NULL OR (percentage >= 0 AND percentage <= 1)),
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE("goal_id", "investment_id"),
  CHECK ("goal_id" != "investment_id")
);

-- Add indexes for performance
CREATE INDEX "idx_goal_investment_link_goal" ON "public"."goal_investment_link"("goal_id");
CREATE INDEX "idx_goal_investment_link_investment" ON "public"."goal_investment_link"("investment_id");

-- Enable RLS on goal_investment_link table
ALTER TABLE "public"."goal_investment_link" ENABLE ROW LEVEL SECURITY;

-- RLS policy for goal_investment_link
-- Allow all operations if auth.uid() matches the client's advisor
CREATE POLICY "Enable all operations for advisor"
ON "public"."goal_investment_link"
AS PERMISSIVE
FOR ALL
TO authenticated
USING (
  (SELECT auth.uid()) = (
    SELECT client.advisor
    FROM "public"."investment"
    JOIN "public"."portfolio" ON investment.portfolio_id = portfolio.id
    JOIN "public"."client" ON portfolio.client = client.id
    WHERE investment.id = goal_investment_link.goal_id
  )
);

-- Enable realtime for goal_investment_link
ALTER PUBLICATION supabase_realtime ADD TABLE "public"."goal_investment_link";
