name: Update App

on:
  push:
    branches: [main]

env:
  PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
  PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
  STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
  PUBLIC_ORIGIN: ${{ vars.PUBLIC_ORIGIN_PROD }}
  PUBLIC_DISABLE_PAYWALL: ${{ vars.PUBLIC_DISABLE_PAYWALL }}
  PUBLIC_DISCORD_LINK: ${{ vars.PUBLIC_DISCORD_LINK }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  RESEND_AUDIENCE_ID: ${{ secrets.RESEND_AUDIENCE_ID }}
  MARKETSTACK_API_KEY: ${{ secrets.MARKETSTACK_API_KEY }}
  SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
